name:        hebrew-time
version:     0.1.1
synopsis:    Hebrew dates and prayer times.
description: Conversion to and from Hebrew dates.
category:    Data
author:      Michael Snoyman <michael@snoyman.com>
maintainer:  Michael Snoyman <michael@snoyman.com>
license:     MIT
github:      snoyberg/hebrew-time

dependencies:
- base >=4 && <5
- time >=1.1.3

library:
  ghc-options: -Wall
  source-dirs: src

tests:
  runtests:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - hebrew-time
    - hspec
    - QuickCheck
