name:        hebrew-time
version:     0.1.1
synopsis:    Hebrew dates and prayer times.
description: Conversion to and from Hebrew dates.
category:    Data
author:      Michael Snoyman <michael@snoyman.com>
maintainer:  Michael Snoyman <michael@snoyman.com>
license:     MIT
github:      snoyberg/hebrew-time

library:
  ghc-options: -Wall
  source-dirs: src
  dependencies:
  - base >=4 && <5
  - time >=1.1.3

tests:
  runtests:
    main: runtests.hs
    source-dirs: src test
    ghc-options: -Wall
    cpp-options: -DTEST
    dependencies:
    - test-framework
    - test-framework-quickcheck2
    - test-framework-hunit
    - HUnit
    - base
    - time
    - QuickCheck >=2 && <3
